Sources:
https://medium.com/biaslyai/pytorch-introduction-to-neural-network-feedforward-neural-network-model-e7231cff47cb
https://github.com/christianversloot/machine-learning-articles/blob/main/how-to-create-a-neural-network-for-regression-with-pytorch.md


##### Importing basic libraries

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import random
random.seed(123)

##### Importing PyTorch libraries

In [23]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score 


##### Importing the data

In [14]:
loans_data = pd.read_csv("../../DATA/loans.csv")
loans_data = loans_data.drop('id', axis=1)
loans_data.head()


Approve  FICO  Income  employed
0        1   531   24536         1
1        0   363   55184         0
2        0   536   49581         0
3        1   567   47146         1
4        1   709   79956         1

In [15]:

loans_data = loans_data.values
loans_train, loans_test = train_test_split(loans_data, test_size= 0.2)

x_train = loans_train[:,:2]
x_test = loans_test[:,:2]

y_train = loans_train[:,3]
y_test = loans_test[:,3]

In [16]:
logistic_model = LogisticRegression()
logistic_model.fit(x_train,y_train)

y_pred = logistic_model.predict(x_test)

In [18]:
accuracy = accuracy_score(y_test,y_pred)*100
confusion_mat = confusion_matrix(y_test,y_pred)

In [19]:
print("Accuracy is",accuracy)
print("Confusion Matrix")
print(confusion_mat)

Accuracy is 83.0
Confusion Matrix
[[  4  33]
 [  1 162]]


In [21]:
print(logistic_model.coef_)
print(logistic_model.intercept_)

[[ 4.47644484e+00 -1.17132804e-03]]
[0.72776414]


# Ridge

In [31]:
logistic_model_ridge = linear_model.RidgeClassifier(alpha = 0.5)
logistic_model_ridge.fit(x_train, y_train)

y_pred = logistic_model_ridge.predict(x_test)

In [33]:
accuracy = accuracy_score(y_test,y_pred)*100
confusion_mat = confusion_matrix(y_test,y_pred)


In [35]:
print("Accuracy is",accuracy)
print("Confusion Matrix")
print(confusion_mat)

Accuracy is 84.0
Confusion Matrix
[[  8  29]
 [  3 160]]


# Lasso